-- Import clients data from CSV
-- This file was generated from cliente.csv

BEGIN;

INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (1, 'Ana Caracas', '98 9971 3335', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (2, 'Joao Caracas', '98 8868 2274', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (3, 'Almir São Luis', '98 9971 2232', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (4, 'Walbinho São Luis', '98 9148 1192', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (5, 'Rogerio Luna', '98 9971 8155', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (6, 'Esposa Almir', NULL, NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (7, 'Claude Troisgrois', '+55 21 99790-7888', NULL, 'Rio', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (8, 'Renato Ciuchini', '+55 21 98122-8807', NULL, 'Rio', 'amigo Claude', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (9, 'Joao Vieira', '+55 22 99766-5684', NULL, 'Buzios', 'Filho Luis Buzios', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (10, 'Luis Vieira', '+55 11 94236-1008', NULL, 'Buzios', 'Filho Luis Buzios', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (11, 'Luiz Lobo', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (12, 'Dico Tostes', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (13, 'Seth Roberts', NULL, 'sethito@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (14, 'Troy Johnson', NULL, 'johnson.troy@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (15, 'Jeff Dickson', NULL, 'jeffTdickson@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (16, 'Kip Davis', NULL, 'daviskip@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (17, 'Greg Watts', NULL, 'g.allenwatts@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (18, 'Andres Santacruz Londoño', NULL, NULL, 'Mexico', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (19, 'Pedro Serpa Coelho', '21 97956 0448', NULL, 'BRA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (20, 'Marco Mondino', '+39 342 631 9846', NULL, 'Italia', 'VAI TRAZER UM GRUPO EM 2022', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (21, 'Alexandre Ludolf', '11 98711 8711', NULL, 'Mexico', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (22, 'Paco Gonzalez', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (23, 'Paulo Ramos', NULL, NULL, 'BRA', 'Barao, do classico', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (24, 'Benedicte Severinsen', '+47 902 05 152', 'Benedicte.severinsen@gmail.com', 'Norway', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (25, 'Marie-Frederique Montel', NULL, 'marie-frederique.montel@usherbrooke.ca', 'Canada', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (26, 'Melanie Smith', NULL, 'Melanie@ddfocus.co.uk', 'Inglaterra', 'Namorada Max', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (27, 'Vince Viky', NULL, 'vinceviky@libero.it', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (28, 'Ricardo Horta', NULL, NULL, 'Rio', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (29, 'Jose Valdecantos Alvarez', NULL, 'josekavaldeka@gmail.com', 'Espanha', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (30, 'Hugo Gotuzzo', '+51 998 291 472', 'hugogotuzzo@esa.pe', 'Peru', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (31, 'Jose Heighes', '+1 (954) 294-6988', 'joseheighes@gmail.com', 'Peru', 'Pepe', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (32, 'Barry Ritchey', NULL, 'barryxwind@msn.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (33, 'Kathi Ritchey', NULL, NULL, 'USA', 'não veleja', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (34, 'Tess Ritchey', NULL, NULL, 'USA', 'não veleja', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (35, 'Raul Nogueira', NULL, NULL, 'BRA', 'não veleja, genro do Barry', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (36, 'Doug Knight', '+1 (541) 410-1372', 'knightandcompany@bendcable.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (37, 'Ed Parton', '+1 (541) 410-6587', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (38, 'Peter Rodgers', NULL, NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (39, 'Joel Moore', '+1 (541) 325-3443', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (40, 'Chris Dire', NULL, NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (41, 'Andreas Sauerbrey', NULL, NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (42, 'Jonathan Haerter', '+1 (970) 376-4761', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (43, 'Chad Fleischer', NULL, NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (44, 'David Baugh', '+1 (206) 618-6881', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (45, 'Marcelo Starling', '+55 11 99720 6669', 'marcelodstarling@gmail.com', 'SP', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (46, 'James Barabas', '+44 7710 111 601', 'info@capetownkiteclub.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (47, 'Cyril Chatelain', '+33 6 31 11 49 88', 'cflchatel@gmail.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (48, 'Maria Flores', NULL, NULL, NULL, 'mulher Cyril', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (49, 'Liam Chatelain Flores', NULL, NULL, NULL, 'Filho Cyril', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (50, 'Fynn Chatelain Flores', NULL, NULL, NULL, 'Filho Cyril', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (51, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (52, 'Artur Juca', '98 8863 0007', NULL, 'São Luis', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (53, 'Enzo', '+34 667 04 49 72', 'mail2enzo@gmail.com', 'Italia', 'Amigo Fede bastardo', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (54, 'Marcio Juca', NULL, NULL, 'Fortaleza', 'interessado rota delta agosto', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (55, 'Alan Kahl', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (56, 'Cedric Teniere Buchot', '+33 6 27 66 24 39', 'ctb@smart-invest.fr', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (57, 'Rally dos Sertoes', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (58, 'Paulo Mauricio Gomes', '21 976791207', 'mauricioinvest@hotmail.com', 'RJ', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (59, 'Edilson', '11 971110973', NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (60, 'Jane Perpere', NULL, NULL, 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (61, 'Luiz Fernando Alves Ferreira', '(11)99403-0616', 'luizferreira77@gmail.com', 'Brasil', 'Amigo Kuzolitz', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (62, 'Juliana Yamashiro', '(11)97609-2748', NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (63, 'Eric Yamashiro Ferreira', NULL, NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (64, 'Hugo Pestana Boto', '21 99617-8649', NULL, 'Brasil', 'irmao vitonha', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (65, 'Rogério Andrade de As', '(11) 98794.0009', 'rogerio.andrade.sa@gmail.com', 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (66, 'Fernando Lami Coelho', NULL, NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (67, 'Greg Martineau', '+1 (360) 820-4645', 'greg@gagecre.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (68, 'Carlos Camargo', NULL, 'ccamargo@partners.org', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (69, 'Murray McCaig', '+14167288240', 'Murray.mccaig@gmail.com', 'Canada', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (70, 'Bruno Baeta', '+5531999936363', NULL, 'Brasil', 'Amigo Cintra', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (71, 'Andre Cintra', '+5511999323040', NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (72, 'Peter Michael Gottschalk', NULL, NULL, 'Brasil', 'Amigo Cintra', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (73, 'Hugo Kendi Nakagawa', NULL, NULL, 'Brasil', 'Amigo Cintra', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (74, 'Rogerio Grao', NULL, NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (75, 'Bruno de Morais Cocian', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (76, 'Olivier Kretz', '+33 6 63 16 56 54', NULL, 'Franca', 'amigo Cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (77, 'Jean Hugues Masgnaux', '+33 6 76 75 86 88', 'jh.masg@gmail.com', 'Franca', 'amigo Cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (78, 'Maria Espanhola', NULL, NULL, 'Espanha', 'Vive em Martinique', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (79, 'Teresa Borges Coutinho', '+351935139007', NULL, 'Portugal', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (80, 'Brett Hatton', NULL, NULL, 'EUA', 'Amigo Bowen, vive em La Ventana, no Mexico', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (81, 'Dani Carioca', '+55 21 99801-4060', NULL, 'RJ', 'interessada no delta de out', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (82, 'Federico Rigotti', '+393493276747', NULL, 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (83, 'John Chesney', NULL, 'j.chesney@F5.com', 'EUA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (84, 'Brian Hart', NULL, 'bhartdds@gmail.com', 'EUA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (85, 'Jeff Knapp', NULL, 'jeff.knapp555@hotmail.com', 'EUA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (86, 'Marilia Guimaraes Fonseca', '+5579991915051', NULL, 'Brasil', 'Aracaju', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (87, 'Paolo Battini', '+33 6 37 22 18 37', NULL, 'Italia', 'Paulino the Devil', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (88, 'Gianluca Sforza', '+39 345 107 7771', 'Gianluca@briviosforza.com', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (89, 'Stephen Long', '+1 (312) 513-5283', 'Slong@antunovich.com', 'EUA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (90, 'Alex Kluge', '+41 75 411 50 19', 'Alexthesurfer.Kluge@gmail.com', 'Suica', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (91, 'Martino Zucchi', NULL, 'Zucchi.martino@gmail.com', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (92, 'Nemanja Marinovic', '+33 6 70 98 05 36', 'nemanja.marinovic@arcelormittal.com', 'Servia', 'Vive em Paris', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (93, 'Lana Filipcic', NULL, 'Lana.Filipcic@t.ht.hr', 'Croacia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (94, 'Frank de Vos', NULL, 'frank.devos156@gmail.com', 'Holanda', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (95, 'Maarten van Berckel', '+31653645408', 'maartenvanberckel@icloud.com', 'Holanda', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (96, 'Daphne Brinkhuis', NULL, 'daphne.brinkhuis@icloud.com', 'Holanda', 'namorada Frank de Vos', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (97, 'Erica Picciani', '(85)996204809', 'ericapicciani95@gmail.com', 'Brasil', 'Esposa Marcel Van Zon', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (98, 'Marcel van Zon', '+31 0623415211', 'info@vanzonrealisatie.nl', 'Holanda', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (99, 'Emanuele Zanchi', '+41 79 849 65 26', 'zanchi.emanuele@gmail.com', 'Suica', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (100, 'Nicolas', '+598 97 109 145', 'nicolasrisso@adinet.com.uy', 'Uruguai', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (101, 'Renato Carvalho do Nascimento', '+55 11 98136-5972', NULL, 'Brasil', 'SP', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (102, 'Fabio Hansen', '+55 11 99265-1009', NULL, 'Brasil', 'SP', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (103, 'Andre Laport Ribeiro', '+1 (646) 201-6935', NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (104, 'Paulo Andre Teixeira Kimaid', '+55 19 98184-8148', NULL, 'Brasil', 'SP', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (105, 'Fernando Azevedo Ferreira', '+55 11 96400-3373', NULL, 'Brasil', 'SP', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (106, 'Clayton de Camargo Campos', '+55 11 98244-7988', NULL, 'Brasil', 'SP', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (107, 'Alan Meikle', '+1 (604) 729-6836', 'alanmeikle@gmail.com', 'Canada', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (108, 'Sabine Wood', '+44 7572 780726', 'Sabine.wood@wood.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (109, 'Richard Wood', '+44 7572 780724', NULL, 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (110, 'Max Ragan', '+1 516 865 7257', 'maksio@msn.com', 'Polonia', 'Cunhado Erica', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (111, 'Nikolaus Raad', '+49 178 8142441', 'mail@dr-raab.com', 'Alemanha', 'Indicacao Kuzolitz', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (112, 'Teresa Stahlhofer', '+49 1512 6892509', 'Teresa.stahlhofer@gmail.com', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (113, 'Nat Roura', '+1 (786) 395-8630', 'natroura@gmail.com', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (114, 'Julien Austruy', '+33662838404', 'j.austruy@gmail.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (115, 'Pierre Barrier', '+33663190990', 'p.barrier@gmail.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (118, 'Katherine Miller', '+1 281-646-2868', 'Ktmille@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (119, 'Caleb Parisher', '+1 713-470-7993', 'Cp103092@yahoo.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (120, 'Eivind Severinsen', '+4740408047', 'Eivind.severinsen@gmail.com', 'Noruega', 'Marido Beneditcte', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (121, 'Alan Macchetta', '+39 335 834 0442', 'alan.macchetta@ormak.it', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (122, 'Alberto Raffa', '+39 347 461 5300', 'Albertoraffa78@gmail.com', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (123, 'Hayden Jonas', '+27 83 555 5911', 'haydenjonas58@gmail.com', 'Africa do Sul', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (124, 'Paul Niven', '+44 7944 703265', 'paul_niven@icloud.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (126, 'Tobit Gamp', '+49 176 24379106', 'tobit.gamp@hotmail.de', 'Alemanha', 'Marido Diana Nanova', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (127, 'Diana Nanova', '+49 176 61088774', 'diana.nanova@gmail.com', 'Alemanha', 'Mulher de Tobit Gamp', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (128, 'Samuel Jackson', '+447852758640', 'jackson.a.samuel@gmail.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (129, 'James Summerfield', '+1 (646) 267-6500', 'Jamessummerfield@mac.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (132, 'Josselin Mahot', '+33 6 77 15 52 81', NULL, 'Franca', 'Produtor de efeitos especiais', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (133, 'Tanguy Magnaux', '+33 6 66 01 16 63', NULL, 'Franca', 'Filho de Jean Hugues Magnaux', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (134, 'Francesco bormioli', '+39 335 534 2476', 'Francesco.bormioli@gmail.com', 'Italia', 'Amigo do Gianluca do Prea', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (135, 'Rod Baker', '+1 (416) 602-0651', 'Rodnbaker@aim.com', 'Canada', 'Amigo Richard wood', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (136, 'Ekaterina Baker', '+16478628086', 'Katsb1@gmail.com', 'Canada', 'Esposa Rod Baker', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (137, 'Shawn Trudeau', '+1 (315) 382-5894', 'shawn.trudeau@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (138, 'Zach Poehlman', '+81 80-7422-4365', 'Zach.poehlman@gmail.com', 'Japao', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (139, 'Allan Karlson', '+1 (850) 461-4520', 'Akarlson7@proton.me', 'USA', 'California', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (140, 'Catrine Hassler', '+41 79 440 94 76', 'chassler@hotmail.com', 'Suica', 'Esposa do Martin Stiller', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (141, 'Martin Stiller', '+41 79 756 51 55', 'martin.stiller@bluewin.ch', 'Suica', 'Marido da Catrine Hassler', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (142, 'André Luiz Freire de Carvalho Kato', '+55 11 96574-7220', 'andre.lfck@gmail.com', 'Brasil', 'Natural de Petrolina', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (143, 'Riccardo Cosentino', '+1 (416) 356-1978', 'riccardo@cosentino.co.uk', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (144, 'Daniel Leppert', '+55 21 98181-9014', NULL, 'Equador', 'Mora no RJ', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (145, 'Christian ???', '+1 (646) 565-8844', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (146, 'Volker', '+49 160 96301855', NULL, 'Alemanha', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (147, 'Carter Wheeler', '239-877-7626', 'Carterwheeler@gmail.com', '?', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (148, 'Jill Wheeler', '239-595-3199', 'Hello@jillwheeler.com', '?', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (149, 'Terry Stonich', '+1 (303) 513-4698', 'Stonichontheroad@yahoo.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (150, 'Avery Stonich', '+1 (303) 638-1586', 'Averystonich@comcast.net', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (151, 'Maxime Robert-Schreyers', '+32 476 40 19 21', 'maxime.robert.s@gmail.com', 'Belgica', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (152, 'Isaac', '+1 (858) 999-4656', NULL, 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (153, 'Andrew Lunt', '+44 7817 033334', 'andrewlunt43@gmail.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (154, 'Giles Pascoe', '+44 7768 453379', 'Giles.pascoe@sky.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (155, 'Andy Culp', '+1 (203) 313-3138', 'Andy@heli.life', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (156, 'Freddie Schweizer', '+1 (203) 247-1733', NULL, 'USA', 'Grupo do Andy Culp', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (157, 'Charles Stone', '+1 (786) 423-7391', NULL, 'USA', 'Grupo do Andy Culp', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (158, 'Jonathan Thesenga', '+1 (801) 243-6969', NULL, 'USA', 'Grupo do Andy Culp', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (159, 'Cecilia Lopes', '+55 21 99974-2304', NULL, 'Brasil', 'Não veleja. Turismo trad. Retiro do Viegas', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (160, 'Matthew Waterhouse', '+44 7714 684080', 'mattwaterhouse@hotmail.com', 'UK', 'amigo do Andrew Lunt e Giles Pascoe', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (161, 'Adrian Van Berckel', NULL, NULL, 'Holanda', 'Filho do Maarten', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (162, 'João Carlos Valente Sequeira Cabeçadas', '+351 916 830 841', 'dorelhas@gmail.com', 'Portugal', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (163, 'Ricardo Biederman  de Carvalho', NULL, NULL, 'Brasil', 'Marido Cecilia Lopes', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (164, 'Marco Intelvi', '+34 625 14 34 71', 'Marco.intelvi@hotmail.it', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (165, 'Edoardo Stazi', '+39 342 516 2463', 'Edoardostazi90@yahoo.it', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (166, 'Miguel Nogales Tovey', '+34 628 07 61 12', 'miguelnogales@yahoo.com', 'Espanha', 'Amigo Richard Wood', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (167, 'Lulu Wood', '+44 7572 780729', NULL, 'UK', 'Filha Richard Wood', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (168, 'Emilio Ricardo Colombo', '+55 48 9989-2309', NULL, 'Brasil', 'de Floripa', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (169, 'Em Ledingham', '+1 907 209 9133', 'emledingham@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (170, 'Allison Mulcahy', '+1 907 723 0306', 'allison.mulcahy@gmail.com', 'USA', 'Amigo Em Ledingham', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (171, 'David Pfeiffer', '+1 (650) 703-3509', 'david.pfeiffer82@gmail.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (172, 'Yann Miosec', '+33 6 82 56 28 18', 'Yann.miossec@gmail.com', 'Franca', 'Amigo Olivier Kretz', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (173, 'Cathou Catherine Bernes', '+33 6 10 27 80 55', NULL, 'Franca', 'grupo antigo cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (174, 'Caroline Wittock', '+32 475 36 11 82', NULL, 'Franca', 'grupo antigo cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (175, 'Stephane Buisseret', '+32 475 43 14 39', NULL, 'Franca', 'Marido Katerine, amigo cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (176, 'Katherine Van Thillo', '+32 475 68 70 11', NULL, 'Franca', 'Esposa Stephane, amiga cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (177, 'Fernando Delvecchio', '+1 (813) 401-6554', 'Delve001@hotmail.com', 'Argentino', 'Mora nos EUA', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (178, 'Dennis Yerokhin', '+1 (978) 618-4226', 'dyerokhin@gmail.com', 'Russia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (179, 'Andrea Stelet Passarinho', '+55 21 99374-6960', NULL, 'Brasil', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (180, 'Damien Langlois Meurinne', '+33 6 24 85 01 98', NULL, 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (181, 'Hamid Belarbi', '+31 6 29388139', 'hamid_belarbi24@hotmail.com', 'Holanda', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (182, 'Juan Cruz Adrogue', '+54 9 11 4477-7158', 'juancruzadrogue@chapelco.com', 'Argentina', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (183, 'Sochi', '+54 9 11 4479-0197', NULL, 'Argentina', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (184, 'Maximilien Merckx', '+58 412-9929545', 'Maxmerckxl@gmail.com', '?', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (185, 'Thierry Rosselin', '+33 6 82 40 36 80', NULL, 'Franca', 'Amigo Cedric', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (186, 'John Amato', '+1 (414) 702-7755', 'Jramato@amatoauto.com', 'USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (187, 'Dmitry Seliverstov', '+1 (215) 436-7191', 'dmitrybills@gmail.com', 'Russia / USA', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (188, 'Martin Bavington', '+44 7545 609040', 'Martin.bavinton@btinternet.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (189, 'Alexander Wit', '+34 647 42 07 22', 'alexwit@gmail.com', 'Holanda', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (190, 'Jean Derély', '+34 653 13 66 83', 'jderely@gmail.com', 'Belgica', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (191, 'Guenter Hoellerl', '+43 664 1231145', NULL, 'Austria', 'Passport Number: U7163278', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (192, 'Anthony Dow', '+34 666 43 30 04', 'Anthony.dow@gmail.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (193, 'Julien castel', '+972586401600', 'castel20@yahoo.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (194, 'Maxime Didier', '+33 6 07 23 69 80', 'maxime.didier@me.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (195, 'Vicenzo Pirro', '+39 334 351 4223', NULL, 'Italia', 'Cliente que veio pela Nicole', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (196, 'Carlos Camargo', '+1 (650) 770-9170', '"ccamargo@', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (197, 'Maximilian Haensel', '+49 171 2727183', 'maximilian.haensel@gmail.com', 'Alemanha', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (198, 'Riccardo Danesi', '+39 331 618 5411', 'riccardo.danesi95@gmail.com', 'Italia', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (199, 'Mario Chiesa', '+39 349 762 5841', 'mariochiesa@hotmail.it', 'Italia', 'Amigo Riccardo Danesi', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (200, 'Ludovico Molossi', NULL, 'Ludovico.molossi@gmail.com', 'Italia', 'Amigo Riccardo Danesi', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (201, 'Andrea Marino', NULL, 'andreamrn08@gmail.com', 'Italia', 'Amigo Riccardo Danesi', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (202, 'Bill Plautz', '+1 (415) 961-8785', NULL, 'US', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (203, 'Neftali Victoria', '+52 1 777 120 3322', 'altacalidad@hotmail.com', 'Mexico', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (204, 'Damien Coens', '+32 475 63 43 00', NULL, 'Belgica', 'Amigo Scatt', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (205, 'Daniel Plautz', NULL, NULL, 'US', 'Filho do Bill', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (206, 'Xavier Chauffour', '+33 6 19 98 31 43', NULL, 'Franca', 'Amigo Cathou, de Toulouse', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (207, 'Clara Marie Terrien', '+31 6 24847190', NULL, 'Franca', 'Mora em Amsterdan', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (208, 'Tiago Almeida', '+27 72 089 3492', 'Tiago.almeida@me.com', 'Brasil', 'Mora em Mozambique', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (209, 'Neil Lapping', '+44 7876 327017', 'Neil.lapping@macsadventure.com', 'UK', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (210, 'Nicolas Laporta', '+32497347734', 'laportanicolas@gmail.com', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (211, 'Didier Hamoir', '+32475744848', 'sherwood@arcadis.be', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (212, 'Gilles Vander Meerschen', '+32475744546', 'gilles@spreds.com', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (213, 'Thierry Plasch', '+32475418288', 'thierry@miseajour.be', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (214, 'Jean-Charles Dupont', '+32477459388', 'charliedupont@icloud.com', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (215, 'Michel de Launoit', '+32475495050', 'michel@tournesol.be', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (216, 'Frederic Bouvy', '+32475436969', 'fred@woodsterhotel.com', 'Belgica', 'Grupo Damien Coens', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (217, 'Andrew Headley', NULL, NULL, NULL, 'Grupo Miguel Nogales', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (218, 'Miguel Santos', NULL, NULL, NULL, 'Grupo Miguel Nogales', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (219, 'Bo Hawkes', '+1 (978) 891-2018', NULL, 'US', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (220, 'Conner Dimoush', '+1 (214) 557-3723', 'cdimoush@gmail.com', 'US', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (221, 'Brad Wickens', '+44 7770 802788', NULL, 'UK', 'Cliente do Bozoh', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (222, 'Mederic Lavigne Delville', '+33 6 81 26 25 23', 'mederic.ld@outlook.com', 'Franca', NULL, NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (223, 'James Kuzolitz', '+44 7730 639310', NULL, 'UK', 'Cliente do Alex', NULL, NULL);
INSERT INTO clients (id, nome_cliente, tel_celular, email, nacionalidade, obs, cpf, data_nasc) VALUES (224, 'Luis Barroso', NULL, 'luisbp123@yahoo.es', 'Espanha', 'Amigo Jose Valdecanto', NULL, NULL);

COMMIT;